/*
 * generated by Xtext
 */
package com.leo_sa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.leo_sa.ui.internal.ReqLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ReqLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ReqLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ReqLangActivator.getInstance().getInjector(ReqLangActivator.COM_LEO_SA_REQLANG);
	}
	
}
