/*
* generated by Xtext
*/
package com.leo_sa.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.leo_sa.services.ReqLangGrammarAccess;

public class ReqLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ReqLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.leo_sa.parser.antlr.internal.InternalReqLangParser createParser(XtextTokenStream stream) {
		return new com.leo_sa.parser.antlr.internal.InternalReqLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ReqLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ReqLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
