/*
 * generated by Xtext
 */
package com.leo_sa.ui.contentassist

import com.leo_sa.ui.contentassist.AbstractReqLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ReqLangProposalProvider extends AbstractReqLangProposalProvider {
}
