/*
* generated by Xtext
*/
package com.leo_sa;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ReqLangUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.leo_sa.ui.internal.ReqLangActivator.getInstance().getInjector("com.leo_sa.ReqLang");
	}
	
}
