/*
 * generated by Xtext
 */
package com.leo_sa;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ReqLangRuntimeModule extends com.leo_sa.AbstractReqLangRuntimeModule {

}
