/**
 * generated by Xtext
 */
package com.leo_sa.validation;

import com.leo_sa.validation.AbstractReqLangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ReqLangValidator extends AbstractReqLangValidator {
}
