/*
 * generated by Xtext
 */
package com.leo_sa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ReqLangUiModule extends com.leo_sa.ui.AbstractReqLangUiModule {
	public ReqLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
