/*
 * generated by Xtext
 */
package com.leo_sa.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractReqLangValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.leo_sa.reqLang.ReqLangPackage.eINSTANCE);
		return result;
	}
}
